### ISSUE TITLE
Need feature detection

### ISSUE THREAD

**Issue by alvestrand** [alvestrand/webrtc-media-streams#1]
Apps that require this feature in order to work need the ability to feature detect it; setting up a PeerConnection and making a connection in order to detect that nothing happens seems like it's too complicated.

**Comment by fippo** [comment]
```
const supportsInsertableStreams =
      !!RTCRtpSender.prototype.createEncodedVideoStreams;
```
as you've done [here](https://github.com/webrtc/samples/pull/1276/commits/c8c0f784199526b38c67faae0e45b01bad681742) seems fine. Arguably should check existence of window.RTCRtpSender ;-)
