### ISSUE TITLE
Data channels

### ISSUE THREAD

**Issue by Codeusa** [alvestrand/webrtc-media-streams#14]
If we're able to use Streams on underlying video and audio data, it stands to reason we should also have that ability on data channels themselves.  Given how difficult it is to effectively address  backpressure using the traditional Javascript event model, the Streams API can give a huge performance win to developers.

**Comment by fippo** [comment]
that is a different issue - I think https://github.com/w3c/webrtc-pc/issues/1732

**Comment by alvestrand** [comment]
Now it is https://github.com/w3c/webrtc-nv-use-cases/issues/44, since it became clear that nobody had the bandwidth to actually propose and implement an API for this in the WebRTC 1.0 timeframe.
