### ISSUE TITLE
rename to createEncodedStreams?

### ISSUE THREAD

**Issue by fippo** [alvestrand/webrtc-media-streams#23]
can we rename createEncodedVideoStreams and createEncodedAudioStreams to createEncodedStreams? The sender kind is always known and can not change so having to decide which method to call is a bit cumbersome

**Comment by guidou** [comment]
I like this idea. @alvestrand WDYT?

**Comment by alvestrand** [comment]
Makes sense to me.
(wild speculation) Should we go whole hog on deep hierarchy and add a superclass RTCRtpSenderOrReceiver that is a parent class of both sender and receiver, and move common methods there?
That's not a job for an extension, it's a job for the main spec, but if it's a Bad Idea for other reasons, we can abandon it on this bug.
(Common attributes / functions: track, transport, getCapabilities, getStats. getParameters and setParameters aren't the same, they have different arg types.)

**Comment by fippo** [comment]
this will also simplify checking for support where we (for "historical reasons") recommend checking for `createEncodedVideoStreams`

**Comment by alvestrand** [comment]
Should we also collapse the two booleans in RTCConfiguration, so that we either have to call createEncodedStreams on every sender/receiver, or on none of them?

**Comment by fippo** [comment]
while we're at it, can we remove the 'force' from the configuration? It will still be forced but this seems like an experimental name.
