### ISSUE TITLE
Document the choice of using streams

### ISSUE THREAD

**Issue by youennf** [alvestrand/webrtc-media-streams#27]
It would be good to determine and write down the pros and cons of this approach.
This could be done in the spec or directly in this issue.

**Comment by youennf** [comment]
Some pros:
- Using streams for streaming makes sense
- streams are available with an existing ecosystem to piggy back on, like worker integration
- ability to add native processing as well as do JS processing

Some questions:
- The pipeline usually dislikes buffering and is more interested in reducing delays. Is back pressure useful here? Is there anything that should be done if the processing takes too much time?
- An application can potentially buffer frames or skip them in JS. What is the impact on the pipeline?
- Errors (decoding, encryption...) are usually recoverable for the pipeline, streams expect errors to be terminal.
- There might be a need to complement streams with additional APIs (for instance trigger intra or FIR), either as API or as frames in the pipe.

**Comment by alvestrand** [comment]
I think pros & cons is one of the things one uses explainers for. I'll add some text there and see if it looks good.

Backpressure isn't particularly useful. For some apps (those that aren't in a hurry), it might be acceptable; in other apps, backpressure should lead to frame discard, not to frame delay.

Skipping frames is OK (it's the app's responsibility to then skip frames depending on the skipped ones). Delaying frames should work too, but reordering them would break; I added language to address this in #29 

I do worry about the signals that travel in the opposite direction (congestion signals and downstream FIRs, for instance). The app should be able to see them and modify them in the cases where that makes sense, but it's not obvious to me how that should be seen.

**Comment by youennf** [comment]
> The app should be able to see them and modify them in the cases where that makes sense, but it's not obvious to me how that should be seen.

I can see the app wanting to have some control of both input (say encoder) and output (say packetiser). APIs (and events) running in a context out of the main thread, representing the pipeline, seems like a natural model to me, as you probably guessed ;). Say I receive a FIR request, an event could be fired and preventDefault could be executed if the app wants its own specific behavior.
That said, the first question is whether this is needed. For instance, which use cases do you envision for the app to actually modify the signals going from one to the other, (say cancel a FIR request)?
