### ISSUE TITLE
Race conditions with async/await inside transform streams

### ISSUE THREAD

**Issue by murillo128** [alvestrand/webrtc-media-streams#28]
The crypto.subtle encrypt/decrypt functions returns a promise, so the call to the transform function of the TransformStream is not guaranteed to finish before the next frame is processed. 

That could cause frame order to be reversed and image decoded with artifacts (specially on large frames vs short ones, or if the encrypted frame contains signature infos in SFrame)

This is solvable in the js (although not easily), but not sure if we could do anything to make things easier for devs.

**Comment by alvestrand** [comment]
I think we need to document the behavior of the API when things like this happen.
I would suggest that frames MUST be delivered in order by metadata.timestamp, and that out-of-order frames will be dropped. @guidou sounds right?

**Comment by guidou** [comment]
Yes, that sounds right
